version: '2'
services:
  ml:
    image: "store/marklogicdb/marklogic-server:10.0-2-dev-centos"
    environment: 
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=false
    ports:
      - "16000-16003:8000-8003"
      - "17000-17001:17000-17001"
    hostname: "mltestdotnet"
    container_name: "mltestdotnet"
    volumes:
      - "./test/cert:/tmp/cert"