version: '2'
services:
  ml:
    image: "mlregistry.marklogic.com/marklogic/ml-10.0-2.1"
    ports:
      - "16000-16003:8000-8003"
      - "17000-17001:17000-17001"
    hostname: "mltestdotnet.local"
    container_name: "mltestdotnet.local"